services:
  sav-edr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sav-edr
    environment:
      PORT: 8080
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL:-onboarding@resend.dev}
      CONTACT_TO_EMAIL: ${CONTACT_TO_EMAIL:-contact@saurabhadvani.online}
    ports:
      - "8081:8080"
    restart: unless-stopped
